---
abstract: 'HTML::Template::Compiled renderer for Mojo'
author:
  - 'Renee Baecker <module@renee-baecker.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoX-Renderer-HTC
requires:
  HTML::Template::Compiled: 0.99
  Mojolicious: 3.51
version: 0.01
